services:
  opencode:
    build: .
    container_name: opencode_wrapper
    runtime: sysbox-runc
    tty: true
    stdin_open: true
    init: true
    working_dir: "${OPENCODE_DIR:-$PWD}"
    environment:
      OPENCODE_DISABLE_AUTO_UPDATE: "1"
    volumes:
      - "${OPENCODE_WORKDIR:-$PWD}:{OPENCODE_WORKDIR:-$PWD}"
      - ./config:/root/.config/opencode
      - ./data:/root/.local/share/opencode
